In [1]:
#                     @title Data Assessing and Cleaning | DSMP 2022-23

###Data Analysis Process
Asking Questions
Data Wrangling
###1. Gathering Data -
i. CSV files - ii.
 APIs -
 iii. Web Scraping -
 iv. Databases
###2. Assessing Data
###3. Cleaning Data
###4. Exploratory Data Analysisn(EDA)
###5. Drawing Conclusion
###6. Comunicating Results

###Summary of today's session
a). You have to become Sherlock\
b). Will try to create a framework\
c). Frameworks may vary\
e). The goal is to give you idea


##1. Data Wrangling
a). Data Gathering\
b). Data Accessing\
c). Data Cleaning


###1b. Data Accessing
In this step, the data is to be understood more deeply. Before implementing methods to clean it, you will definitely need to have a better idea about what the data is about.

##Types of Unclean Data
There are 2 kinds of unclean data\
##Dirty Data (Data with Quality issues):
 Dirty data, also known as low quality data. Low quality data has content\ issues.

a). Duplicated data\
b). Missing Data\
c). Corrupt Data\
d). Inaccurate Data

##Messy Data (Data with tidiness issues):
Messy data, also known as untidy data. Untidy data has structural issues.Tidy data has the following properties:

a). Each variable forms a column\
b). Each observation forms a row\
c). Each observational unit forms a table

In [2]:
#load libaries:
import numpy as np
import pandas as pd

In [3]:
# @title LOAD DATASET

#load Dataset:
patient=pd.read_csv('patients.csv')
treatment=pd.read_csv('treatments.csv')
adverse_reaction=pd.read_csv('adverse_reactions.csv')
treatment_cut=pd.read_csv('treatments_cut.csv')

##1. Write a summary for your data:
This is a dataset about 500 patients of which 350 patients participated in a clinical trial. None of the patients were using Novodra (a popular injectable insulin) or Auralin (the oral insulin being researched) as their primary source of insulin before. All were experiencing elevated HbA1c levels.

All 350 patients were treated with Novodra to establish a baseline HbA1c level and insulin dose. After 4 weeks, which isn’t enough time to capture all the change in HbA1c that can be attributed by the switch to Auralin or Novodra:

a). 175 patients switched to Auralin for 24 weeks\
b). 175 patients continued using Novodra for 24 weeks\
Data about patients feeling some adverse effects is also recorded.



##Table -> patients:
1). patient_id: the unique identifier for each patient in the Master Patient Index (i.e. patient database) of the pharmaceutical company that is producing Auralin\
2). assigned_sex: the assigned sex of each patient at birth (male or female)\
3). given_name: the given name (i.e. first name) of each patient\
4). surname: the surname (i.e. last name) of each patient\
5). address: the main address for each patient\
6). city: the corresponding city for the main address of each patient\
7). state: the corresponding state for the main address of each patient\
8). zip_code: the corresponding zip code for the main address of each patient\
9). country: the corresponding country for the main address of each patient (all United states for this clinical trial)\
10)> contact: phone number and email information for each patient\
11)> birthdate: the date of birth of each patient (month/day/year). The inclusion criteria for this clinical trial is age >= 18 (there is no maximum age because diabetes is a growing problem among the elderly population)\
12). weight: the weight of each patient in pounds (lbs)\
13)> height: the height of each patient in inches (in)\
14). bmi: the Body Mass Index (BMI) of each patient. BMI is a simple calculation using a person's height and weight. The formula is BMI = kg/m2 where kg is a person's weight in kilograms and m2 is their height in metres squared. A BMI of 25.0 or more is overweight, while the healthy range is 18.5 to 24.9. The inclusion criteria for this clinical trial is 16 >= BMI >= 38.



##Table -> treatments and treatment_cut:
1). given_name: the given name of each patient in the Master Patient Index that took part in the clinical trial\
2). surname: the surname of each patient in the Master Patient Index that took part in the clinical trial\
3). auralin: the baseline median daily dose of insulin from the week prior to switching to Auralin (the number before the dash) and the ending median daily dose of insulin at the end of the 24 weeks of treatment measured over the 24th week of treatment (the number after the dash). Both are measured in units (shortform 'u'), which is the international unit of measurement and the standard measurement for insulin.\
4). novodra: same as above, except for patients that continued treatment with Novodra\
5). hba1c_start: the patient's HbA1c level at the beginning of the first week of treatment. HbA1c stands for Hemoglobin A1c. The HbA1c test measures what the average blood sugar has been over the past three months. It is thus a powerful way to get an overall sense of how well diabetes has been controlled. Everyone with diabetes should have this test 2 to 4 times per year. Measured in %.\
6). hba1c_end: the patient's HbA1c level at the end of the last week of treatment\
7). hba1c_change: the change in the patient's HbA1c level from the start of treatment to the end, i.e., hba1c_start - hba1c_end. For Auralin to be deemed effective, it must be "noninferior" to Novodra, the current standard for insulin. This "noninferiority" is statistically defined as the upper bound of the 95% confidence interval being less than 0.4% for the difference between the mean HbA1c changes for Novodra and Auralin (i.e. Novodra minus Auralin).


##Table -> adverse_reactions
1). given_name: the given name of each patient in the Master Patient Index that took part in the clinical trial and had an adverse reaction (includes both patients treated Auralin and Novodra)\
2). surname: the surname of each patient in the Master Patient Index that took part in the clinical trial and had an adverse reaction (includes both patients treated Auralin and Novodra)\
3). adverse_reaction: the adverse reaction reported by the patient\

##3. Add any additional information
###Additional useful information:

a). Insulin resistance varies person to person, which is why both starting median daily dose and ending median daily dose are required, i.e., to calculate change in dose.\
b). It is important to test drugs and medical products in the people they are meant to help. People of different age, race, sex, and ethnic group must be included in clinical trials. This diversity is reflected in the patients table.\

###4 Types of Assessment
###There are 2 types of assessment styles

a). Manual - Looking through the data manually in google sheets\
b). Programmatic - By using pandas functions such as info(), describe() or sample()


##Steps in Assessment
###There are 2 steps involved in Assessment

1). Discover\
2). Document

In [4]:
patient.head()

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
0,1,female,Zoe,Wellish,576 Brown Bear Drive,Rancho California,California,92390.0,United States,951-719-9170ZoeWellish@superrito.com,7/10/1976,121.7,66,19.6
1,2,female,Pamela,Hill,2370 University Hill Road,Armstrong,Illinois,61812.0,United States,PamelaSHill@cuvox.de+1 (217) 569-3204,4/3/1967,118.8,66,19.2
2,3,male,Jae,Debord,1493 Poling Farm Road,York,Nebraska,68467.0,United States,402-363-6804JaeMDebord@gustr.com,2/19/1980,177.8,71,24.8
3,4,male,Liêm,Phan,2335 Webster Street,Woodbridge,NJ,7095.0,United States,PhanBaLiem@jourrapide.com+1 (732) 636-8246,7/26/1951,220.9,70,31.7
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303.0,United States,334-515-7487TimNeudorf@cuvox.de,2/18/1928,192.3,27,26.1

In [5]:
treatment.head()

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,veronika,jindrová,41u - 48u,-,7.63,7.20,NaN
1,elliot,richardson,-,40u - 45u,7.56,7.09,0.97
2,yukitaka,takenaka,-,39u - 36u,7.68,7.25,NaN
3,skye,gormanston,33u - 36u,-,7.97,7.62,0.35
4,alissa,montez,-,33u - 29u,7.78,7.46,0.32

In [6]:
treatment_cut.head()

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,jožka,resanovič,22u - 30u,-,7.56,7.22,0.34
1,inunnguaq,heilmann,57u - 67u,-,7.85,7.45,NaN
2,alwin,svensson,36u - 39u,-,7.78,7.34,NaN
3,thể,lương,-,61u - 64u,7.64,7.22,0.92
4,amanda,ribeiro,36u - 44u,-,7.85,7.47,0.38

In [7]:
adverse_reaction.head()

  given_name     surname           adverse_reaction
0      berta  napolitani  injection site discomfort
1       lena        baer               hypoglycemia
2     joseph         day               hypoglycemia
3     flavia  fiorentino                      cough
4    manouck     wubbels          throat irritation

In [8]:
treatment.shape

(280, 7)

In [9]:
treatment_cut.shape

(70, 7)

In [10]:
with pd.ExcelWriter('clinical_trials.xlsx') as writer:
  patient.to_excel(writer,sheet_name='patients')
  treatment.to_excel(writer,sheet_name='treatments')
  treatment_cut.to_excel(writer,sheet_name='treatments_cut')
  adverse_reaction.to_excel(writer,sheet_name='adverse_reactions')

##Issues with the dataset
1). Dirty Data
Table - Patients

- patient_id = 9 has misspelled name 'Dsvid' instead of David `accuracy`
- state col sometimes contain full name and some times abbrivietation `consistency`
- zip code col has entries with 4 digit `validity`
- data missing for 12 patients in address,city, state,zip_code  ,country,   contact `completion`
- incorrect data type assigned to sex, zip code, birthdate `validity`
- duplicate entries by the name of John Doe `accuracy`
- one patient has weight = 48 pounds `accuracy`
- one patient has height = 27 inches `accuracy`
Table - Treatments & Treatments_cut

- given_name and surname col is is all lower case `consistency`
- remove u from Auralin and Novadra cols `validity`
- '-' in novadra and Auralin col treated as nan `validity`
- missing values in hba1c_change col `completion`
- 1 duplicate entry by the name Joseph day `accuracy`
- in hba1c_change 9 instead of 4 `accuracy`
Table - Adverse_reactions

- given_name and surname are all in lower case `consistency`

##Messy Data
Table - Patients

- contact col contains both phone and email
Table - Treatments & Treatments_cut

- Auralin and Novadra col should be split into 2 cols start and end dose
- merge both the tables
Table - Adverse_reactions

- This table should not exist independently

##Automatic Assessment
- head and tail
- sample
- info
- isnull
- duplicated
- describe

In [11]:
patient.head()

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
0,1,female,Zoe,Wellish,576 Brown Bear Drive,Rancho California,California,92390.0,United States,951-719-9170ZoeWellish@superrito.com,7/10/1976,121.7,66,19.6
1,2,female,Pamela,Hill,2370 University Hill Road,Armstrong,Illinois,61812.0,United States,PamelaSHill@cuvox.de+1 (217) 569-3204,4/3/1967,118.8,66,19.2
2,3,male,Jae,Debord,1493 Poling Farm Road,York,Nebraska,68467.0,United States,402-363-6804JaeMDebord@gustr.com,2/19/1980,177.8,71,24.8
3,4,male,Liêm,Phan,2335 Webster Street,Woodbridge,NJ,7095.0,United States,PhanBaLiem@jourrapide.com+1 (732) 636-8246,7/26/1951,220.9,70,31.7
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303.0,United States,334-515-7487TimNeudorf@cuvox.de,2/18/1928,192.3,27,26.1

In [12]:
patient.tail()

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
498,499,male,Mustafa,Lindström,2530 Victoria Court,Milton Mills,ME,3852.0,United States,207-477-0579MustafaLindstrom@jourrapide.com,4/10/1959,181.1,72,24.6
499,500,male,Ruman,Bisliev,494 Clarksburg Park Road,Sedona,AZ,86341.0,United States,928-284-4492RumanBisliev@gustr.com,3/26/1948,239.6,70,34.4
500,501,female,Jinke,de Keizer,649 Nutter Street,Overland Park,MO,64110.0,United States,816-223-6007JinkedeKeizer@teleworm.us,1/13/1971,171.2,67,26.8
501,502,female,Chidalu,Onyekaozulu,3652 Boone Crockett Lane,Seattle,WA,98109.0,United States,ChidaluOnyekaozulu@jourrapide.com1 360 443 2060,2/13/1952,176.9,67,27.7
502,503,male,Pat,Gersten,2778 North Avenue,Burr,Nebraska,68324.0,United States,PatrickGersten@rhyta.com402-848-4923,5/3/1954,138.2,71,19.3

In [13]:
patient.sample()

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
144,145,male,Mile,Stanić,4640 Windy Ridge Road,Fort Wayne,IN,46804.0,United States,260-591-5755MileStanic@dayrep.com,10/31/1961,244.9,71,34.2

In [14]:
patient.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   patient_id    503 non-null    int64
 1   assigned_sex  503 non-null    object
 2   given_name    503 non-null    object
 3   surname       503 non-null    object
 4   address       491 non-null    object
 5   city          491 non-null    object
 6   state         491 non-null    object
 7   zip_code      491 non-null    float64
 8   country       491 non-null    object
 9   contact       491 non-null    object
 10  birthdate     503 non-null    object
 11  weight        503 non-null    float64
 12  height        503 non-null    int64
 13  bmi           503 non-null    float64
dtypes: float64(3), int64(2), object(9)
memory usage: 55.1+ KB

In [15]:
patient.describe()

       patient_id      zip_code      weight      height         bmi
count  503.000000    491.000000  503.000000  503.000000  503.000000
mean   252.000000  49084.118126  173.434990   66.634195   27.483897
std    145.347859  30265.807442   33.916741    4.411297    5.276438
min      1.000000   1002.000000   48.800000   27.000000   17.100000
25%    126.500000  21920.500000  149.300000   63.000000   23.300000
50%    252.000000  48057.000000  175.300000   67.000000   27.200000
75%    377.500000  75679.000000  199.500000   70.000000   31.750000
max    503.000000  99701.000000  255.900000   79.000000   37.700000

In [16]:
#Check Missing value some column:
patient[patient['address'].isnull()]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
209,210,female,Lalita,Eldarkhanov,NaN,NaN,NaN,NaN,NaN,NaN,8/14/1950,143.4,62,26.2
219,220,male,Mỹ,Quynh,NaN,NaN,NaN,NaN,NaN,NaN,4/9/1978,237.8,69,35.1
230,231,female,Elisabeth,Knudsen,NaN,NaN,NaN,NaN,NaN,NaN,9/23/1976,165.9,63,29.4
234,235,female,Martina,Tománková,NaN,NaN,NaN,NaN,NaN,NaN,4/7/1936,199.5,65,33.2
242,243,male,John,O'Brian,NaN,NaN,NaN,NaN,NaN,NaN,2/25/1957,205.3,74,26.4
249,250,male,Benjamin,Mehler,NaN,NaN,NaN,NaN,NaN,NaN,10/30/1951,146.5,69,21.6
257,258,male,Jin,Kung,NaN,NaN,NaN,NaN,NaN,NaN,5/17/1995,231.7,69,34.2
264,265,female,Wafiyyah,Asfour,NaN,NaN,NaN,NaN,NaN,NaN,11/3/1989,158.6,63,28.1
269,270,female,Flavia,Fiorentino,NaN,NaN,NaN,NaN,NaN,NaN,10/9/1937,175.2,61,33.1
278,279,female,Generosa,Cabán,NaN,NaN,NaN,NaN,NaN,NaN,12/16/1962,124.3,69,18.4
286,287,male,Lewis,Webb,NaN,NaN,NaN,NaN,NaN,NaN,4/1/1979,155.3,68,23.6
296,297,female,Chỉ,Lâm,NaN,NaN,NaN,NaN,NaN,NaN,5/14/1990,181.1,63,32.1

In [17]:
#Basic Information:
treatment.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 280 entries, 0 to 279
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   given_name    280 non-null    object
 1   surname       280 non-null    object
 2   auralin       280 non-null    object
 3   novodra       280 non-null    object
 4   hba1c_start   280 non-null    float64
 5   hba1c_end     280 non-null    float64
 6   hba1c_change  171 non-null    float64
dtypes: float64(3), object(4)
memory usage: 15.4+ KB

In [18]:
#Check Missing value specif column
treatment[treatment['hba1c_change'].isnull()]

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,veronika,jindrová,41u - 48u,-,7.63,7.20,NaN
2,yukitaka,takenaka,-,39u - 36u,7.68,7.25,NaN
8,saber,ménard,-,54u - 54u,8.08,7.70,NaN
9,asia,woźniak,30u - 36u,-,7.76,7.37,NaN
10,joseph,day,29u - 36u,-,7.70,7.19,NaN
...,...,...,...,...,...,...,...
269,hiromu,horikawa,-,47u - 46u,7.77,7.28,NaN
271,leo,vieira,-,30u - 33u,7.74,7.36,NaN
273,kate,wilkinson,36u - 39u,-,7.72,7.20,NaN
274,naja,enoksen,43u - 50u,-,7.98,7.59,NaN
276,john,teichelmann,-,49u - 49u,7.90,7.58,NaN

In [19]:
#Check Baic information:
treatment_cut.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   given_name    70 non-null     object
 1   surname       70 non-null     object
 2   auralin       70 non-null     object
 3   novodra       70 non-null     object
 4   hba1c_start   70 non-null     float64
 5   hba1c_end     70 non-null     float64
 6   hba1c_change  42 non-null     float64
dtypes: float64(3), object(4)
memory usage: 4.0+ KB

In [20]:
#Check Missing value:
treatment_cut[treatment_cut['hba1c_change'].isnull()]

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
1,inunnguaq,heilmann,57u - 67u,-,7.85,7.45,NaN
2,alwin,svensson,36u - 39u,-,7.78,7.34,NaN
6,sara,miles,30u - 35u,-,7.53,7.12,NaN
7,frydryk,adamski,63u - 74u,-,7.75,7.27,NaN
8,jane,citizen,-,37u - 38u,7.98,7.60,NaN
11,gabriela,michalčíková,26u - 36u,-,8.37,7.97,NaN
14,chiho,higa,-,46u - 46u,7.71,7.30,NaN
17,emma,barlow,48u - 57u,-,7.85,7.39,NaN
21,david,villadsen,26u - 39u,-,7.86,7.40,NaN
24,lóa,hrafnsdóttir,22u - 31u,-,7.60,7.09,NaN
28,una,traustadóttir,-,35u - 34u,8.00,7.50,NaN
30,trifon,izmailov,58u - 63u,-,7.68,7.28,NaN
38,guðni,heimisson,-,40u - 36u,7.64,7.24,NaN
39,maryam,dratchev,37u - 45u,-,9.91,9.46,NaN
43,hans peter,radislav,42u - 53u,-,7.60,7.20,NaN
44,jeremy,montagu,-,52u - 52u,7.68,7.36,NaN
45,štefanija,novosel,37u - 42u,-,7.64,7.17,NaN
47,regolo,nucci,51u - 59u,-,7.53,7.02,NaN
51,bjørnar,nilsen,-,36u - 33u,7.99,7.70,NaN
52,vivien,zsinkó,30u - 38u,-,8.35,7.92,NaN
54,borna,šlezinger,-,42u - 41u,7.55,7.18,NaN
55,mary,adams,-,32u - 33u,7.65,7.26,NaN
56,blanka,jurković,31u - 43u,-,7.77,7.33,NaN
60,maret,sultygov,-,26u - 23u,7.67,7.30,NaN
62,fakhri,fakhoury,39u - 50u,-,7.83,7.39,NaN
63,žarka,rap,35u - 48u,-,7.54,7.15,NaN
68,berta,napolitani,-,42u - 44u,7.68,7.21,NaN
69,armina,sauvé,36u - 46u,-,7.86,7.40,NaN

In [21]:
#Check Basic Information:
adverse_reaction.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   given_name        34 non-null     object
 1   surname           34 non-null     object
 2   adverse_reaction  34 non-null     object
dtypes: object(3)
memory usage: 948.0+ bytes

In [22]:
patient.duplicated().sum()

np.int64(0)

In [23]:
#Check duplicated value in two column:
patient.duplicated(subset=['given_name','surname']).sum()

np.int64(5)

In [24]:
#Sum of duplicated value:
patient['patient_id'].duplicated().sum()

np.int64(0)

In [25]:
#Check duplicated value:
patient[patient.duplicated(subset=['given_name','surname'])]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
229,230,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
237,238,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
244,245,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
251,252,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
277,278,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4

In [26]:
#Sum of dupliacte value:
treatment.duplicated().sum()

np.int64(1)

In [27]:
#check duplicate value:
treatment[treatment.duplicated()]

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
136,joseph,day,29u - 36u,-,7.7,7.19,NaN

In [28]:
#Check duplicate value in two column:
treatment[treatment.duplicated(subset=['given_name','surname'])]

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
136,joseph,day,29u - 36u,-,7.7,7.19,NaN

In [29]:
#No missing value for treatment_cut column:
treatment_cut[treatment_cut.duplicated(subset=["given_name","surname"])]

Empty DataFrame
Columns: [given_name, surname, auralin, novodra, hba1c_start, hba1c_end, hba1c_change]
Index: []

In [30]:
#Check duplicated value in adverse rection table:

adverse_reaction.duplicated().sum()

np.int64(0)

In [31]:
#Check Mathematical summary on numerical column in patient table:
patient.describe()

       patient_id      zip_code      weight      height         bmi
count  503.000000    491.000000  503.000000  503.000000  503.000000
mean   252.000000  49084.118126  173.434990   66.634195   27.483897
std    145.347859  30265.807442   33.916741    4.411297    5.276438
min      1.000000   1002.000000   48.800000   27.000000   17.100000
25%    126.500000  21920.500000  149.300000   63.000000   23.300000
50%    252.000000  48057.000000  175.300000   67.000000   27.200000
75%    377.500000  75679.000000  199.500000   70.000000   31.750000
max    503.000000  99701.000000  255.900000   79.000000   37.700000

In [32]:
patient[patient['weight']==48.800000]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
210,211,female,Camilla,Zaitseva,4689 Briarhill Lane,Wooster,OH,44691.0,United States,330-202-2145CamillaZaitseva@superrito.com,11/26/1938,48.8,63,19.1

In [33]:
patient[patient['height']==27.000000]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303.0,United States,334-515-7487TimNeudorf@cuvox.de,2/18/1928,192.3,27,26.1

In [34]:
#Check mathamatical summary in treatment table:
treatment.describe()

       hba1c_start   hba1c_end  hba1c_change
count   280.000000  280.000000    171.000000
mean      7.985929    7.589286      0.546023
std       0.568638    0.569672      0.279555
min       7.500000    7.010000      0.200000
25%       7.660000    7.270000      0.340000
50%       7.800000    7.420000      0.380000
75%       7.970000    7.570000      0.920000
max       9.950000    9.580000      0.990000

In [35]:
treatment.sort_values('hba1c_start')

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
113,kari,laatikainen,39u - 43u,-,7.50,7.11,NaN
126,jowita,wiśniewska,-,22u - 23u,7.50,7.08,0.92
270,mika,martinsson,34u - 43u,-,7.50,7.17,0.33
53,nasser,mansour,-,33u - 31u,7.51,7.06,0.95
105,finlay,sheppard,-,31u - 30u,7.51,7.17,0.34
...,...,...,...,...,...,...,...
25,benoît,bonami,-,44u - 43u,9.82,9.40,0.92
171,justyna,kowalczyk,24u - 34u,-,9.84,9.44,NaN
81,robert,wagner,43u - 49u,-,9.84,9.52,0.32
75,mackenzie,mckay,-,44u - 43u,9.87,9.48,0.39
166,annie,allen,36u - 42u,-,9.95,9.58,0.37

In [36]:
treatment.sort_values('hba1c_end')

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
39,krisztina,magyar,-,32u - 27u,7.52,7.01,0.51
80,hideki,haraguchi,-,37u - 35u,7.59,7.05,0.54
53,nasser,mansour,-,33u - 31u,7.51,7.06,0.95
187,león,reynoso,-,38u - 40u,7.59,7.06,0.53
86,ananías,enríquez,-,44u - 45u,7.58,7.07,0.51
...,...,...,...,...,...,...,...
192,valur,bjarkason,-,31u - 36u,9.71,9.41,0.30
171,justyna,kowalczyk,24u - 34u,-,9.84,9.44,NaN
75,mackenzie,mckay,-,44u - 43u,9.87,9.48,0.39
81,robert,wagner,43u - 49u,-,9.84,9.52,0.32
166,annie,allen,36u - 42u,-,9.95,9.58,0.37

In [37]:
treatment.sort_values('hba1c_change',na_position='first')

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,veronika,jindrová,41u - 48u,-,7.63,7.20,NaN
2,yukitaka,takenaka,-,39u - 36u,7.68,7.25,NaN
8,saber,ménard,-,54u - 54u,8.08,7.70,NaN
9,asia,woźniak,30u - 36u,-,7.76,7.37,NaN
10,joseph,day,29u - 36u,-,7.70,7.19,NaN
...,...,...,...,...,...,...,...
49,jackson,addison,-,42u - 42u,7.99,7.51,0.98
17,gina,cain,-,36u - 36u,7.88,7.40,0.98
138,giovana,rocha,-,23u - 21u,7.87,7.38,0.99
32,laura,ehrlichmann,-,43u - 40u,7.95,7.46,0.99
245,wu,sung,-,47u - 48u,7.61,7.12,0.99

In [38]:
treatment_cut.describe()

       hba1c_start  hba1c_end  hba1c_change
count    70.000000  70.000000     42.000000
mean      7.838000   7.443143      0.518810
std       0.423007   0.418706      0.270719
min       7.510000   7.020000      0.280000
25%       7.640000   7.232500      0.340000
50%       7.730000   7.345000      0.370000
75%       7.860000   7.467500      0.907500
max       9.910000   9.460000      0.970000

In [39]:
treatment_cut.sort_values('hba1c_change',na_position='first')

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
1,inunnguaq,heilmann,57u - 67u,-,7.85,7.45,NaN
2,alwin,svensson,36u - 39u,-,7.78,7.34,NaN
6,sara,miles,30u - 35u,-,7.53,7.12,NaN
7,frydryk,adamski,63u - 74u,-,7.75,7.27,NaN
8,jane,citizen,-,37u - 38u,7.98,7.60,NaN
...,...,...,...,...,...,...,...
66,jakob,jakobsen,-,28u - 26u,7.96,7.51,0.95
41,dalmacia,madrid,-,26u - 23u,7.67,7.21,0.96
9,angela,lavrentyev,-,28u - 24u,7.61,7.14,0.97
42,daimy,tromp,-,40u - 45u,9.41,8.94,0.97
34,adlan,shishani,-,43u - 40u,7.84,7.37,0.97

##Note - Assessing Data is an Iterative Process
###Data Quality Dimensions
- Completeness -> is data missing?
- Validity -> is data invalid -> negative height -> duplicate patient id
- Accuracy -> data is valid but not accurate -> weight -> 1kg
- Consistency -> both valid and accurate but written differently -> New Youk and NY

##Order of severity
Completeness <- Validity <- Accuracy <- Consistency

##Data Cleaning Order
1). Quality -> Completeness\
2). Tidiness (Massy data)\
3). Quality -> Validity\
4). Quality -> Accuracy\
5). Quality -> Consistency

##Steps involved in Data cleaning
- Define
- Code
- Test

Always make sure to create a copy of your pandas dataframe before you start the cleaning process

In [40]:
#Copy for all dataset:
patient_df=patient.copy()
treatment_df=treatment.copy()
treatment_cut_df=treatment_cut.copy()
adverse_reaction_df=adverse_reaction.copy()

##Define
- replace all missing values of patients df with no data
- sub hba1c_start from hba1c_end to get all the change values
- in patients table we will use regex to separate email and phone

In [41]:
#Code:
patient_df.fillna('No data avilabel', inplace=True)

/tmp/ipython-input-2146712965.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'No data avilabel' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  patient_df.fillna('No data avilabel', inplace=True)

In [42]:
#Test
patient_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   patient_id    503 non-null    int64
 1   assigned_sex  503 non-null    object
 2   given_name    503 non-null    object
 3   surname       503 non-null    object
 4   address       503 non-null    object
 5   city          503 non-null    object
 6   state         503 non-null    object
 7   zip_code      503 non-null    object
 8   country       503 non-null    object
 9   contact       503 non-null    object
 10  birthdate     503 non-null    object
 11  weight        503 non-null    float64
 12  height        503 non-null    int64
 13  bmi           503 non-null    float64
dtypes: float64(2), int64(2), object(10)
memory usage: 55.1+ KB

In [43]:
#Code:
treatment_df['hba1c_change']=treatment_df['hba1c_start']-treatment_df['hba1c_end']
treatment_cut_df['hba1c_change']=treatment_cut_df['hba1c_start']-treatment_cut_df['hba1c_end']

In [44]:
treatment_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 280 entries, 0 to 279
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   given_name    280 non-null    object
 1   surname       280 non-null    object
 2   auralin       280 non-null    object
 3   novodra       280 non-null    object
 4   hba1c_start   280 non-null    float64
 5   hba1c_end     280 non-null    float64
 6   hba1c_change  280 non-null    float64
dtypes: float64(3), object(4)
memory usage: 15.4+ KB

In [45]:
treatment_cut_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   given_name    70 non-null     object
 1   surname       70 non-null     object
 2   auralin       70 non-null     object
 3   novodra       70 non-null     object
 4   hba1c_start   70 non-null     float64
 5   hba1c_end     70 non-null     float64
 6   hba1c_change  70 non-null     float64
dtypes: float64(3), object(4)
memory usage: 4.0+ KB

In [46]:
import re
def find_contact_details(text: str) -> tuple:
    # it the value is NaN, then return it
    if pd.isna(text):
        return np.nan

    # create the phone number pattern
    phone_number_pattern = re.compile(r"(\+[\d]{1,3}\s)?(\(?[\d]{3}\)?\s?-?[\d]{3}\s?-?[\d]{4})")
    # find the phone number from the value/text, as a result we will get a list
    phone_number  = re.findall(phone_number_pattern, text)

    # if length is 0, then the regex can't find any ph number, then define with NaN
    if len(phone_number) <= 0:
        phone_number = np.nan
    # if the country code is attached with the ph number, for that case, the first
    # element will be the country code and the 2nd element will be the actual ph
    # number. So, get that ph number
    elif len(phone_number) >= 2:
        phone_number = phone_number[1]
    # else, we will get the ph number. Grab it.
    else:
        phone_number = phone_number[0]

    # if we found the ph number (with/without country code), then remove that part from the actual value.
    # after removing the ph number, the remaining string might be the email address.
    possible_email_add = re.sub(phone_number_pattern, "", text).strip()

    # then return the ph number and the email address
    return phone_number, possible_email_add

In [47]:
patient_df['phone'] = patient_df["contact"].apply(lambda x: find_contact_details(x)).apply(lambda x:x[0])
patient_df['email'] = patient_df["contact"].apply(lambda x: find_contact_details(x)).apply(lambda x:x[1])

In [48]:
## Updated code as - code used in the session using append on dataframe, which is now deprecated - removed.

# Initialize a list to collect the data
data = []

# Iterate through the data
for item in patient['contact']:
    # Convert item to a string to ensure compatibility with re.search
    item = str(item)

    # Use regular expressions to find the phone numbers and email addresses
    phone_match = re.search(r'(\d{3}[-\.\s]??\d{3}[-\.\s]??\d{4}|\(\d{3}\)\s*\d{3}[-\.\s]??\d{4}|\d{3}[-\.\s]??\d{4})', item)
    phone = phone_match.group(0) if phone_match else None

    # Remove the phone number from the item
    item = re.sub(r'(\d{3}[-\.\s]??\d{3}[-\.\s]??\d{4}|\(\d{3}\)\s*\d{3}[-\.\s]??\d{4}|\d{3}[-\.\s]??\d{4})', '', item)

    email_match = re.search(r'([a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+)', item)
    email = email_match.group(0) if email_match else None

    data.append({'phone': phone, 'email': email})

# Create a DataFrame from the collected data
df = pd.DataFrame(data, columns=['phone', 'email'])

print(df)

              phone                               email
0      951-719-9170            ZoeWellish@superrito.com
1    (217) 569-3204                PamelaSHill@cuvox.de
2      402-363-6804                JaeMDebord@gustr.com
3    (732) 636-8246           PhanBaLiem@jourrapide.com
4      334-515-7487                 TimNeudorf@cuvox.de
..              ...                                 ...
498    207-477-0579     MustafaLindstrom@jourrapide.com
499    928-284-4492              RumanBisliev@gustr.com
500    816-223-6007           JinkedeKeizer@teleworm.us
501    360 443 2060  ChidaluOnyekaozulu@jourrapide.com1
502    402-848-4923            PatrickGersten@rhyta.com

[503 rows x 2 columns]

In [49]:
#Remove Contact column:
patient_df.drop(columns='contact',inplace=True)

In [50]:
patient_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   patient_id    503 non-null    int64
 1   assigned_sex  503 non-null    object
 2   given_name    503 non-null    object
 3   surname       503 non-null    object
 4   address       503 non-null    object
 5   city          503 non-null    object
 6   state         503 non-null    object
 7   zip_code      503 non-null    object
 8   country       503 non-null    object
 9   birthdate     503 non-null    object
 10  weight        503 non-null    float64
 11  height        503 non-null    int64
 12  bmi           503 non-null    float64
 13  phone         491 non-null    object
 14  email         503 non-null    object
dtypes: float64(2), int64(2), object(11)
memory usage: 59.1+ KB

In [51]:
patient_df = patient_df[pd.to_numeric(patient_df['zip_code'], errors='coerce').notna()]
patient_df['zip_code'] = patient_df['zip_code'].astype(str)
patient_df['birthdate']=patient_df['birthdate'].astype('datetime64[ns]')

In [52]:
patient_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 491 entries, 0 to 502
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   patient_id    491 non-null    int64
 1   assigned_sex  491 non-null    object
 2   given_name    491 non-null    object
 3   surname       491 non-null    object
 4   address       491 non-null    object
 5   city          491 non-null    object
 6   state         491 non-null    object
 7   zip_code      491 non-null    object
 8   country       491 non-null    object
 9   birthdate     491 non-null    datetime64[ns]
 10  weight        491 non-null    float64
 11  height        491 non-null    int64
 12  bmi           491 non-null    float64
 13  phone         491 non-null    object
 14  email         491 non-null    object
dtypes: datetime64[ns](1), float64(2), int64(2), object(10)
memory usage: 61.4+ KB

In [53]:
#Remove Duplicated value:
patient_df = patient_df.drop_duplicates(subset=["given_name", "surname"], keep="first")

In [54]:
#Check duplicated value:
patient_df[patient_df.duplicated(subset=['given_name','surname'])]

Empty DataFrame
Columns: [patient_id, assigned_sex, given_name, surname, address, city, state, zip_code, country, birthdate, weight, height, bmi, phone, email]
Index: []

In [55]:
patient_df.loc[
    (patient_df['patient_id'] == 9) & (patient_df['given_name'] == "Dsvid"),
    'given_name'
] = "David"

In [56]:
# Convert to string and pad with leading zeros
patient_df['zip_code'] = patient_df['zip_code'].astype(str).str.zfill(5)

In [57]:
!pip install us

Collecting us
  Downloading us-3.2.0-py3-none-any.whl.metadata (10 kB)
Collecting jellyfish (from us)
  Downloading jellyfish-1.2.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.6 kB)
Downloading us-3.2.0-py3-none-any.whl (13 kB)
Downloading jellyfish-1.2.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (355 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 355.9/355.9 kB 20.6 MB/s eta 0:00:00
Installing collected packages: jellyfish, us
Successfully installed jellyfish-1.2.0 us-3.2.0

In [58]:
import us

patient_df['state'] = patient_df['state'].apply(lambda x: us.states.lookup(x).name if us.states.lookup(x) else x)

In [59]:
# Define reasonable adult ranges
ranges = {
    "weight": (70, 400),   # lbs
    "height": (55, 84)     # inches
}

# Impute values outside the range with column median
for col, (low, high) in ranges.items():
    median_val = patient_df[col].median()
    patient_df[col] = patient_df[col].apply(
        lambda x: median_val if x < low or x > high else x
    )

In [60]:
patient_df.describe()

,patient_id,birthdate,weight,height,bmi
count,486.000000,486,486.000000,486.000000,486.000000
mean,251.991770,1958-09-23 17:52:35.555555584,173.536728,66.670782,27.491770
min,1.000000,1921-11-06 00:00:00,102.100000,59.000000,17.100000
25%,122.250000,1938-03-07 18:00:00,149.250000,63.000000,23.200000
50%,253.500000,1958-12-01 00:00:00,174.575000,67.000000,27.200000
75%,381.750000,1978-04-11 06:00:00,199.725000,70.000000,31.700000
max,503.000000,1999-07-03 00:00:00,255.900000,79.000000,37.700000
std,147.806895,NaN,33.607133,4.030637,5.295547

In [61]:
patient_df

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,birthdate,weight,height,bmi,phone,email
0,1,female,Zoe,Wellish,576 Brown Bear Drive,Rancho California,California,92390.0,United States,1976-07-10,121.7,66.0,19.6,"(, 951-719-9170)",ZoeWellish@superrito.com
1,2,female,Pamela,Hill,2370 University Hill Road,Armstrong,Illinois,61812.0,United States,1967-04-03,118.8,66.0,19.2,"(+1 , (217) 569-3204)",PamelaSHill@cuvox.de
2,3,male,Jae,Debord,1493 Poling Farm Road,York,Nebraska,68467.0,United States,1980-02-19,177.8,71.0,24.8,"(, 402-363-6804)",JaeMDebord@gustr.com
3,4,male,Liêm,Phan,2335 Webster Street,Woodbridge,New Jersey,7095.0,United States,1951-07-26,220.9,70.0,31.7,"(+1 , (732) 636-8246)",PhanBaLiem@jourrapide.com
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,Alabama,36303.0,United States,1928-02-18,192.3,67.0,26.1,"(, 334-515-7487)",TimNeudorf@cuvox.de
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,499,male,Mustafa,Lindström,2530 Victoria Court,Milton Mills,Maine,3852.0,United States,1959-04-10,181.1,72.0,24.6,"(, 207-477-0579)",MustafaLindstrom@jourrapide.com
499,500,male,Ruman,Bisliev,494 Clarksburg Park Road,Sedona,Arizona,86341.0,United States,1948-03-26,239.6,70.0,34.4,"(, 928-284-4492)",RumanBisliev@gustr.com
500,501,female,Jinke,de Keizer,649 Nutter Street,Overland Park,Missouri,64110.0,United States,1971-01-13,171.2,67.0,26.8,"(, 816-223-6007)",JinkedeKeizer@teleworm.us
501,502,female,Chidalu,Onyekaozulu,3652 Boone Crockett Lane,Seattle,Washington,98109.0,United States,1952-02-13,176.9,67.0,27.7,"(, 360 443 2060)",ChidaluOnyekaozulu@jourrapide.com1
502,503,male,Pat,Gersten,2778 North Avenue,Burr,Nebraska,68324.0,United States,1954-05-03,138.2,71.0,19.3,"(, 402-848-4923)",PatrickGersten@rhyta.com

In [62]:
patient_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 486 entries, 0 to 502
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   patient_id    486 non-null    int64
 1   assigned_sex  486 non-null    object
 2   given_name    486 non-null    object
 3   surname       486 non-null    object
 4   address       486 non-null    object
 5   city          486 non-null    object
 6   state         486 non-null    object
 7   zip_code      486 non-null    object
 8   country       486 non-null    object
 9   birthdate     486 non-null    datetime64[ns]
 10  weight        486 non-null    float64
 11  height        486 non-null    float64
 12  bmi           486 non-null    float64
 13  phone         486 non-null    object
 14  email         486 non-null    object
dtypes: datetime64[ns](1), float64(3), int64(1), object(10)
memory usage: 60.8+ KB

In [63]:
#Concate treatment And treatment_cut Table:
treatment_df=pd.concat([treatment_df,treatment_cut_df],ignore_index=True)

In [64]:
treatment_df

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,veronika,jindrová,41u - 48u,-,7.63,7.20,0.43
1,elliot,richardson,-,40u - 45u,7.56,7.09,0.47
2,yukitaka,takenaka,-,39u - 36u,7.68,7.25,0.43
3,skye,gormanston,33u - 36u,-,7.97,7.62,0.35
4,alissa,montez,-,33u - 29u,7.78,7.46,0.32
...,...,...,...,...,...,...,...
345,rovzan,kishiev,32u - 37u,-,7.75,7.41,0.34
346,jakob,jakobsen,-,28u - 26u,7.96,7.51,0.45
347,bernd,schneider,48u - 56u,-,7.74,7.44,0.30
348,berta,napolitani,-,42u - 44u,7.68,7.21,0.47
349,armina,sauvé,36u - 46u,-,7.86,7.40,0.46

In [65]:
treatment_df=treatment_df.melt(id_vars=['given_name','surname','hba1c_start','hba1c_end','hba1c_change'],var_name='Type',value_name='dosage_range')

In [66]:
#'-' Remove in dosage range column:
treatment_df=treatment_df[treatment_df['dosage_range']!='-']

In [67]:
treatment_df

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,Type,dosage_range
0,veronika,jindrová,7.63,7.20,0.43,auralin,41u - 48u
3,skye,gormanston,7.97,7.62,0.35,auralin,33u - 36u
6,sophia,haugen,7.65,7.27,0.38,auralin,37u - 42u
7,eddie,archer,7.89,7.55,0.34,auralin,31u - 38u
9,asia,woźniak,7.76,7.37,0.39,auralin,30u - 36u
...,...,...,...,...,...,...,...
688,christopher,woodward,7.51,7.06,0.45,novodra,55u - 51u
690,maret,sultygov,7.67,7.30,0.37,novodra,26u - 23u
694,lixue,hsueh,9.21,8.80,0.41,novodra,22u - 23u
696,jakob,jakobsen,7.96,7.51,0.45,novodra,28u - 26u
698,berta,napolitani,7.68,7.21,0.47,novodra,42u - 44u

In [68]:
#Split dosage range value:
treatment_df['dosage_start']=treatment_df['dosage_range'].str.split('-').str.get(0)

In [69]:
#Split dosage range value:
treatment_df['dosage_end']=treatment_df['dosage_range'].str.split('-').str.get(1)

In [70]:
#Remove Dosage range column:
treatment_df.drop(columns='dosage_range',inplace=True)

In [71]:
#Repalce 'u' in  dosage start and dosage end column:
treatment_df['dosage_start']=treatment_df['dosage_start'].str.replace('u','')
treatment_df['dosage_end']=treatment_df['dosage_end'].str.replace('u','')

In [72]:
#Convert data tyype object to int for two column like  dosage start & end:
treatment_df['dosage_start']=treatment_df['dosage_start'].astype('int')
treatment_df['dosage_end']=treatment_df['dosage_end'].astype('int')

In [73]:
treatment_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 350 entries, 0 to 698
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   given_name    350 non-null    object
 1   surname       350 non-null    object
 2   hba1c_start   350 non-null    float64
 3   hba1c_end     350 non-null    float64
 4   hba1c_change  350 non-null    float64
 5   Type          350 non-null    object
 6   dosage_start  350 non-null    int64
 7   dosage_end    350 non-null    int64
dtypes: float64(3), int64(2), object(3)
memory usage: 24.6+ KB

In [74]:
#Merg treatment and adverse rection table:
treatment_df=pd.merge(treatment_df,adverse_reaction_df,on=['given_name','surname'],how='left')

In [75]:
treatment_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   given_name        350 non-null    object
 1   surname           350 non-null    object
 2   hba1c_start       350 non-null    float64
 3   hba1c_end         350 non-null    float64
 4   hba1c_change      350 non-null    float64
 5   Type              350 non-null    object
 6   dosage_start      350 non-null    int64
 7   dosage_end        350 non-null    int64
 8   adverse_reaction  35 non-null     object
dtypes: float64(3), int64(2), object(4)
memory usage: 24.7+ KB

In [76]:
#First letter capital:
treatment_df['given_name'] = treatment_df['given_name'].str.title()
treatment_df['surname'] = treatment_df['surname'].str.title()

In [77]:
# Joseph Day ke duplicates hata ke sirf ek row rehne do
mask = (treatment_df['given_name'] == 'Joseph') & (treatment_df['surname'] == 'Day')
treatment_df = pd.concat([
    treatment_df[~mask],                               # baaki sab data as it is
    treatment_df[mask].drop_duplicates(keep='first')   # Joseph Day ka sirf ek row
])

In [78]:
treatment_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 349 entries, 0 to 5
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   given_name        349 non-null    object
 1   surname           349 non-null    object
 2   hba1c_start       349 non-null    float64
 3   hba1c_end         349 non-null    float64
 4   hba1c_change      349 non-null    float64
 5   Type              349 non-null    object
 6   dosage_start      349 non-null    int64
 7   dosage_end        349 non-null    int64
 8   adverse_reaction  34 non-null     object
dtypes: float64(3), int64(2), object(4)
memory usage: 27.3+ KB

In [79]:
treatment_df.describe()

       hba1c_start   hba1c_end  hba1c_change  dosage_start  dosage_end
count   349.000000  349.000000    349.000000    349.000000  349.000000
mean      7.957077    7.561117      0.395960     39.100287   43.065903
std       0.545938    0.545878      0.059054      9.307562   10.532310
min       7.500000    7.010000      0.200000     19.000000   21.000000
25%       7.650000    7.270000      0.350000     32.000000   36.000000
50%       7.790000    7.400000      0.390000     39.000000   42.000000
75%       7.950000    7.560000      0.440000     45.000000   50.000000
max       9.950000    9.580000      0.540000     63.000000   75.000000

In [80]:
# Make sure start and end are numeric
treatment_df['hba1c_start'] = pd.to_numeric(treatment_df['hba1c_start'], errors='coerce')
treatment_df['hba1c_end']   = pd.to_numeric(treatment_df['hba1c_end'], errors='coerce')

# Recalculate change
treatment_df['hba1c_change'] = treatment_df['hba1c_start'] - treatment_df['hba1c_end']

In [81]:
treatment_df.sort_values('hba1c_change',na_position='first')

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,Type,dosage_start,dosage_end,adverse_reaction
133,Albina,Zetticci,7.93,7.73,0.20,auralin,45,51,NaN
210,Tosh,Jensen,7.93,7.69,0.24,novodra,51,48,NaN
119,Manouck,Wubbels,7.66,7.40,0.26,auralin,55,62,throat irritation
66,Nicoline,Østergaard,7.84,7.57,0.27,auralin,24,32,NaN
258,Chidalu,Onyekaozulu,7.54,7.27,0.27,novodra,42,41,NaN
...,...,...,...,...,...,...,...,...,...
131,Kate,Wilkinson,7.72,7.20,0.52,auralin,36,39,NaN
267,León,Reynoso,7.59,7.06,0.53,novodra,38,40,NaN
23,Kristoffer,Martinsen,9.18,8.64,0.54,auralin,29,37,NaN
217,Hideki,Haraguchi,7.59,7.05,0.54,novodra,37,35,NaN
91,Kerman,Dandonneau,7.82,7.28,0.54,auralin,41,50,NaN

In [82]:
treatment_df.to_csv('treatment_cleaned.csv',index=False)

In [83]:
patient_df.to_csv('patient_cleaned.csv',index=False)